### ISSUE TITLE
CustomError: Access to requested resource is denied.

### ISSUE THREAD

**Issue by Tanveer-LowCoder** [amz-tools/amazon-sp-api#10]
I get the following error when calling the getOrders operation:

2020-12-26T17:03:52.835Z	5531d3c3-8473-4da8-a4b2-034f137044c5	INFO	CustomError: Access to requested resource is denied.
    at SellingPartner.callAPI (/var/task/node_modules/amazon-sp-api/lib/SellingPartner.js:229:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Runtime.exports.handler (/var/task/index.js:22:15) {
  code: 'Unauthorized',
  details: '',
  type: 'error'
}

When running the same code for my own store:  I get null object back for getOrders - meaning its all working end to end. 

When I try to get the getOrder for a clients store, where we got the spapi_auth correctly, and generated the refresh_token successfully, we hit the error. Unfortunately I only have one clients store to try it out. 

BTW, what is also interesting is that, I did get the result early in the morning with my clients store. I did not change anything, and hence I am a little lost as to what could be throwing this error.

**Comment by Tanveer-LowCoder** [comment]
Not sure what, but this was fixed automatically for some of the API endpoints.

For some, it still exists (Eg: getReport). I'm closing this for the time being.
