### ISSUE TITLE
Some endpoints work, others return 'unauthorized' error message

### ISSUE THREAD

**Issue by wassim-sayerh** [amz-tools/amazon-sp-api#127]
Hello,

Thank you very much for this API, it avoids the super-complicated signature process altogether. However, even though some endpoints work perfectly on my end, for example 'orders' and 'sales', others return an unauthorized error message, for example 'fulfillmentOutbound' and 'catalogItems'.

[Archive.zip](https://github.com/amz-tools/amazon-sp-api/files/8496110/Archive.zip)

Attached are examples of an API call to the 'orders' (working) endpoint and the 'catalogItems' (not working), the latter returning the following :

`accessToken _<SECRET>_
Loaded credentials from config object
CustomError: Access to requested resource is denied.
    at SellingPartner.callAPI (/Users/wassim/js-learn/node_modules/amazon-sp-api/lib/SellingPartner.js:597:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/wassim/js-learn/catalogItems.js:52:21 {
  code: 'Unauthorized',
  details: '',
  type: 'error'
}`

It is true that initially, I had only selected 'Inventory and Order Tracking' and 'Brand Analytics' in the Seller Central app, but I have since then selected all the other roles by editing the app and still the same issue, so I don't think it was coming from that.

Can you please help ?

Thank you.

**Comment by amz-tools** [comment]
HI @wassim-sayerh,

when I try the `listCatalogItems` call you posted I receive an `InvalidInput` error with the message `Required parameter IdType not found`. That's quite misleading as its that parameter can't be specified. But when I either specify `Query` with a keyword or `SellerSKU` I do receive a valid response returning me an `Items` array.

Looking at your error message it also looks like its not the operation but rather the tokens that cause an issue here. What's actually the reason that you manually do a POST via axios to get an access token? I think that shouldn't be necessary as the client handles that for you automatically. Could you try that same call but without the axios POST and without specifying the access token? Let's see if that works.

**Comment by amz-tools** [comment]
Closed due to inactivity.
