### ISSUE TITLE
CustomError Null - Invalid Input

### ISSUE THREAD

**Issue by jamieroyce** [amz-tools/amazon-sp-api#139]
I have been using the SellingPartner for the past several months with no issues and in the last couple days, my production server started returning this `CustomError Null` and I can't track down what the issue is. 

The call I am running is: 
```
		response = await sellingPartner.callAPI({
			operation: 'getOrders',
			endpoint: 'orders',
			query: {
				MarketplaceIds: marketplaceId,
				CreatedAfter: createdAfter,
				MaxResultsPerPage: 100,
				OrderStatuses: status,
			}
		});		

The error is: 
```
Amazon API caught error CustomError: null
    at SellingPartner.callAPI (/home/code/mindcloud-api/node_modules/amazon-sp-api/lib/SellingPartner.js:578:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getAmazonOrders (file:///home/code/mindcloud-api/server/connectors/amazon/getAmazonOrders.js:35:14)
    at async Object.run (file:///home/code/mindcloud-api/server/jobTypes/createOrders.js:92:26)
    at async Object.run (file:///home/code/mindcloud-api/server/jobManager/buildJobInstance.js:117:33)
    at async Object.runInstance (file:///home/code/mindcloud-api/server/jobManager/buildJob.js:27:20)
    at async Object.run (file:///home/code/mindcloud-api/server/lib/jobManager.js:46:29)
    at async postJobRun (file:///home/code/mindcloud-api/server/router/routes/api/postJobRun.js:4:18) {
  code: 'InvalidInput',
  type: 'error'
}
```

The weird thing is the exact same code works fine on my local development server. It only returns the above error on production. Both are going through the same API server, so it shouldn't be an IP issue. But it would help if there was a more clear error message than "Null".

**Comment by amz-tools** [comment]
Hi @jamieroyce,

thats really strange. Probably it has something to do with the params you are passing in being different on development than in production. Could you post the values you are passing in for `MarketplaceIds`, `CreatedAfter`, etc.?

**Comment by jamieroyce** [comment]
I tested with exact same params on both Dev environment and Production environment. Here they are: 
```
MarketplaceIds: "ATVPDKIKX0DER"
CreatedAfter: "2022-06-13T00:00:00.000Z"
OrderStatuses: "Unshipped"
```
Runs same as usual from local machine calling the API. 
In last week, this CustomError Null starting showing up and prevents orders from being processed. 

Is there someway to get a more clear error message of what is causing this?

**Comment by amz-tools** [comment]
@jamieroyce Works for me. You could try with setting `raw_result` to `true` in options, which will give you some more input, i.e. the headers.
