### ISSUE TITLE
relationships and dimensions not working with the library

### ISSUE THREAD

**Issue by lincolnaleixo** [amz-tools/amazon-sp-api#185]
```
operation: 'getCatalogItem'
endpoint: 'catalogItems'
```

When using includedData with "dimensions" or "relationships" , I got this error:

```
CustomError: Request has missing or invalid parameters and cannot be parsed.
    at SellingPartner.callAPI (/Users/robot/Desktop/conquer/node_modules/amazon-sp-api/lib/SellingPartner.js:658:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getListingInfo (/Users/robot/Desktop/conquer/src/listings.js:8:15)
    at async /Users/robot/Desktop/conquer/src/listings.js:38:15 {
  code: 'InvalidInput',
  details: '',
  type: 'error'
}
```

Tried with postman and got no error, tried with multiple ASINs as well

**Comment by lincolnaleixo** [comment]
just found out that you can use different version into the API, so I'm closing it
