### ISSUE TITLE
CustomError: Client authentication failed (code: 'invalid_client')

### ISSUE THREAD

**Issue by vicatcu** [amz-tools/amazon-sp-api#228]
I'm using self authorization with a freshly minted refresh token for my own seller central account. I do the following:

```
const SellingPartnerAPI = require('amazon-sp-api');
const sellingPartner = new SellingPartnerAPI({region: 'na', refresh_token: 'my-self-authorization-refresh-token'});
const body = { ... };
sellingPartner.callAPI(body).then(v => console.log(JSON.stringify(v, null, 2))).catch(e => console.error(e));
```

and that results in...

```
CustomError: Client authentication failed
    at SellingPartner.refreshAccessToken ..../node_modules/amazon-sp-api/lib/SellingPartner.js:554:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SellingPartner._validateAccessTokenAndRoleCredentials (..../node_modules/amazon-sp-api/lib/SellingPartner.js:294:9)
    at async SellingPartner.callAPI (..../node_modules/amazon-sp-api/lib/SellingPartner.js:642:5) {
  code: 'invalid_client',
  type: 'error'
}
```

How do I debug this and fix it? Could it be something about the health of my Seller Central account rather than something about how I'm generating the refresh token?

I'm using the latest version of amazon-spi-api@0.8.4

**Comment by vicatcu** [comment]
I have put some console logging in and tried the same request being made in the library using CURL, and got this result:

```
HTTP/1.1 401 Unauthorized
Server: Server
Date: Thu, 17 Aug 2023 18:15:00 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 77
Connection: keep-alive
x-amz-rid: REDACTED
x-amzn-RequestId: REDACTED
X-Amz-Date: Thu, 17 Aug 2023 18:15:00 GMT
x-amzn-ErrorType: OA2InvalidClientException:http://internal.amazon.com/coral/com.amazon.panda/
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Vary: Content-Type,Accept-Encoding,User-Agent
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload

{"error_description":"Client authentication failed","error":"invalid_client"}
```

**Comment by vicatcu** [comment]
I think I followed all the instructions [here](https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities) in setting up the AWS User, Role, and Policy. And in my application I provide the ARN for the **Role**. I just don't know where this is going wrong. Can someone from the maintainers help me get this up and running? I'm trying to use the API for my own Seller Central account as a 'private' application.

**Comment by vicatcu** [comment]
Some more information that I find strange. When I expand Self-Authorizations, it shows under the heading "Marketplaces": Mexico. I'm actually mostly / only interested in the USA marketplace, and when I create a new SellingPartnerAPI with the constructor I'm specifying `region: 'na'` and the request body I perform `callAPI` with provides marketplace IDs for all North American marketplaces, e.g.:

```
{
  "operation": "getOrders",
  "endpoint": "orders",
  "query": {
    "MarketplaceIds": [
      "ATVPDKIKX0DER",
      "A2Q3Y263D00KWC",
      "A2EUQ1WTGCTBG2",
      "A1AM78C64UM0Y8"
    ],
    "LastUpdatedAfter": "2023-08-16T17:06:35Z"
  }
}

```

**Comment by vicatcu** [comment]
OK, I guess I'm a dunce, I found that there was a file credentials file in ~/.amzspapi/credentials that I had to update all these values in:

SELLING_PARTNER_APP_CLIENT_ID
SELLING_PARTNER_APP_CLIENT_SECRET
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SELLING_PARTNER_ROLE
SELLER_PARTNER_APP_REFRESH_TOKEN

**Comment by vicatcu** [comment]
Closing as overcome by events
