### ISSUE TITLE
I got error The security token included in the request is invalid

### ISSUE THREAD

**Issue by eternalparquet** [amz-tools/amazon-sp-api#97]
When I use the createDestination api I get this error:

```
CustomError: null
    at SellingPartner.callAPI (/home/antonio/Documenti/nodejsserver/node_modules/amazon-sp-api/lib/SellingPartner.js:578:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /server.js:27:17
    at async Server.<anonymous> (/server.js:8:25) {
  code: 'InvalidInput',
  type: 'error'

```

This is the code:
```
`(async() => {
    try {
      let sellingPartner = new SellingPartnerAPI({
        region:'eu', 
        refresh_token: "x",
        options:{
          auto_request_tokens:false,
          only_grantless_operations:true,
        },
        credentials:{
              SELLING_PARTNER_APP_CLIENT_ID: "x",
              SELLING_PARTNER_APP_CLIENT_SECRET: "x",
              AWS_ACCESS_KEY_ID: "x",
              AWS_SECRET_ACCESS_KEY: "x",
              AWS_SELLING_PARTNER_ROLE: "x"
        }        
      });
      await sellingPartner.refreshAccessToken('sellingpartnerapi::notifications');
      await sellingPartner.refreshRoleCredentials();
      let res = await sellingPartner.callAPI({
        operation:'createDestination',
        endpoint:'notifications',
        query:{
          name: "name",
          resourceSpecification:
          {
            sqs:
            {
              arn: "x"
            }
          }        
        }               
      });
      return res;

    } catch(e){
      console.log(e);
      return e;
    }
  })();`
```

If I do not use credentials I get errors.

Is it supported this call?

**Comment by eternalparquet** [comment]
There was a mistacke

**Comment by amz-tools** [comment]
Hi @eternalparquet,

try to not specify the usual refresh token when initializing, I think that will do the trick. Like this:

```
let sellingPartner = new SellingPartnerAPI({
  region:'eu', 
  options:{
    auto_request_tokens:false,
    only_grantless_operations:true
  },
  credentials:{
    ...
  }        
});
```

**Comment by amz-tools** [comment]
@eternalparquet This worked out I think? So we can close this, right?

**Comment by eternalparquet** [comment]
Yes, it worked.

**Comment by erayalakese** [comment]
> try to not specify the usual refresh token when initializing, I think that will do the trick. Like this:

Hello @amz-tools  , I couldn't understand this. How we will specify refresh_token?

**Comment by eternalparquet** [comment]
> 

You can use this code: 
`      await sellingPartner.refreshAccessToken();
`
